### ISSUE TITLE
How to adjust parameters after adding stairs?

### ISSUE THREAD

**Issue by mariusa** [blackears/blenderStairs#4]
How to adjust parameters after adding stairs? (eg width, number of steps...)
Found this related post: https://projects.blender.org/blender/blender-addons/issues/97722 which says the plugin should implement this.

Thanks

**Comment by blackears** [comment]
There's a little panel that appears in the bottom left hand corner of Blender just after you create the stairs object.  Open it to adjust the parameters.

![image](https://github.com/blackears/blenderStairs/assets/6724608/15d212e1-a80a-49cc-8073-d5901836a14d)

![image](https://github.com/blackears/blenderStairs/assets/6724608/bdf92df7-f344-4185-bd56-6b5a1661ee88)

**Comment by mariusa** [comment]
Hi & thanks,

That works right after adding the stairs, but when selecting the stairs later (eg after adding/selecting other objects), it doesn't show anymore. Would it be possible to edit those parameters later after the initial creation?

PS: thanks so much for this plugin, I tried various software (freecad, sketchup...) to try to make some regualar & curved stairs, found all cumbersome as a newbie.

**Comment by blackears** [comment]
I'm afraid not. This is a limitation of Blender.  It might be possible in the future if Blender adds new geometry nodes that allow for scripting, but the way operators are currently designed, you can't change them after you've switched to another object.

Thanks for the kind words!  I was frustrated myself with how cumbersome stairs were to make which is why I came up with the plugin.

**Comment by mariusa** [comment]
I see, thanks again for your support!
